# .envファイルから環境変数を読み込み
if [ -f ".env" ]; then
    export $(grep -v '^#' .env | xargs)
    echo ".envファイルから環境変数を読み込みました"
else
    echo "警告: .envファイルが見つかりません。.env.exampleをコピーして.envを作成してください"
fi

# Forge認証情報
export FORGE_EMAIL="shota.hayashida@ariseanalytics.com"
export FORGE_API_TOKEN="ATATT3xFfGF0QseNlWcKjAJbyYMmKrtOtMNfAY9CaaJWGUwX3qvMOb2nWix95aTqlZ-C1yIwD-k6eYCm3TMkm0v96JmMPgW0cUcPY3p5yY8y4yZxGNJBMtDsskLhIsNuM5cC1ALZbcs0mzPeSecg53z6TP8jp5NBEKQ7xl2WbXGx4ajFWQSsIsc=088CB1B4"
export CHOKIDAR_USEPOLLING=true

# 以下は.envファイルから読み込まれるため、コメントアウト
#forge variables set AGENT_URL http://localhost:9002
# export DEV_TUNNEL_URL="https://231bjm9f-9002.asse.devtunnels.ms"
# export DEV_TUNNEL_URL="https://bd1lkcds-5000.asse.devtunnels.ms"
#export DEV_TUNNEL_TOKEN="eyJhbGciOiJFUzI1NiIsImtpZCI6IkU3NDEzRTg2OEMyOEEzMkZCRkI3MEZBMzk5MkVEMEE1RDVCNjRBNzMiLCJ0eXAiOiJKV1QifQ.eyJjbHVzdGVySWQiOiJhc3NlIiwidHVubmVsSWQiOiJuZWF0LWFudC01NjBtZG1xIiwic2NwIjoiY29ubmVjdCIsImV4cCI6MTc1Mzc3MjE3MSwiaXNzIjoiaHR0cHM6Ly90dW5uZWxzLmFwaS52aXN1YWxzdHVkaW8uY29tLyIsIm5iZiI6MTc1MzY4NDg3MX0.hOSULxw-aLSnXIVpP7nv3j8240mA5QQy12AbkUH7WReoKzLhnGqjQ6QdGAxlaglQb-lkh57GTmefWq0_kZnrKw"
# export DEV_TUNNEL_TOKEN="eyJhbGciOiJFUzI1NiIsImtpZCI6IkU3NDEzRTg2OEMyOEEzMkZCRkI3MEZBMzk5MkVEMEE1RDVCNjRBNzMiLCJ0eXAiOiJKV1QifQ.eyJjbHVzdGVySWQiOiJhc3NlIiwidHVubmVsSWQiOiJuZWF0LWFudC01NjBtZG1xIiwic2NwIjoiY29ubmVjdCIsImV4cCI6MTc1Mzk0OTI5OSwiaXNzIjoiaHR0cHM6Ly90dW5uZWxzLmFwaS52aXN1YWxzdHVkaW8uY29tLyIsIm5iZiI6MTc1MzY2MTk5OX0.a-QQwF4hV3FYfqbf6n9aGYAEID3hzNDkHe_DlEJPWg5brMNE84H7JkNS7hsxwmQBJ5Pkev072037P3thFWd5Rg"
#export DEV_TUNNEL_TOKEN="eyJhbGciOiJFUzI1NiIsImtpZCI6IkU3NDEzRTg2OEMyOEEzMkZCRkI3MEZBMzk5MkVEMEE1RDVCNjRBNzMiLCJ0eXAiOiJKV1QifQ.eyJjbHVzdGVySWQiOiJhc3NlIiwidHVubmVsSWQiOiJmYW5jeS1mb2ctMXZsMzFjZyIsInNjcCI6ImNvbm5lY3QiLCJleHAiOjE3NTQwOTY3MjIsImlzcyI6Imh0dHBzOi8vdHVubmVscy5hcGkudmlzdWFsc3R1ZGlvLmNvbS8iLCJuYmYiOjE3NTQwMDk0MjJ9.VDzTk0WHsZgXV65-Bbw4YdBNyuepmZIee-f4DEcuiVEl1ujYmPeCyuplDVz9h8T9y0W_Z4c2kxwIuJu6D9t2Yw"
# export DEV_TUNNEL_TOKEN="eyJhbGciOiJFUzI1NiIsImtpZCI6IkU3NDEzRTg2OEMyOEEzMkZCRkI3MEZBMzk5MkVEMEE1RDVCNjRBNzMiLCJ0eXAiOiJKV1QifQ.eyJjbHVzdGVySWQiOiJhc3NlIiwidHVubmVsSWQiOiJmYW5jeS1mb2ctMXZsMzFjZyIsInNjcCI6ImNvbm5lY3QiLCJleHAiOjE3NTQzNjYwMTQsImlzcyI6Imh0dHBzOi8vdHVubmVscy5hcGkudmlzdWFsc3R1ZGlvLmNvbS8iLCJuYmYiOjE3NTQyNzg3MTR9.sekCSnv2hPpAXpSE9j1SCt1xbiZpMjr5Y_77hhY99btnAzBG9V8_r-ARWobjRnsx0v1vvQOzi3OFZvzAe2B9DA"
forge variables set DEV_TUNNEL_URL ${DEV_TUNNEL_URL}
forge variables set DEV_TUNNEL_TOKEN ${DEV_TUNNEL_TOKEN}
forge variables list